### PR TITLE
Hsdo 626 filters

### PR DESCRIPTION
**Pull request by sherakama**
#  For review

- Checkout branch HSDO-626-filters
- Enable module capx_filters
- navigate to CAPx Mappers
- Click 'Edit' on desired CAPx Mapper
- in 'Filters' fieldset, click 'Configure Filters'
- Add a single or multiple filters using the same CAP API Path string as allowed in the mapping settings
- Create/Edit an importer to use the mapper with the filters.
- Import/Update Content.
- Validate correct content imported

### CODE REVIEW

**Comment by sherakama** [comment]
@pookmish, Jira smart commits requires that you list all issue keys without special characters

eg: `JRA-123 JRA-234 JRA-345 #resolve some message`
https://confluence.atlassian.com/fisheye/using-smart-commits-298976812.html

**Comment by pookmish** [comment]
DOH

**Comment by pookmish** [comment]
@sherakama, I think this has been greatly improved since we talked. I'm getting very fast imports and correct data in my tests with profiles & publications. As well as no filters & multiple filters.

**Comment by sherakama** [comment]
Rebased and merged in from the filters branch.

**Pull request closed without merging**
