### PR TITLE
Peekmo/JsonPath missing...

### PR DESCRIPTION
**Pull request by mpriest**
Looks like the jsonpath subproject got committed, but .gitmodules is missing. Just commit the source code?

### CODE REVIEW

**Comment by sherakama** [comment]
Thanks for this.

**Comment by mpriest** [comment]
Urgh, just noticed peekmo/jsonpath has very recent commits... I did a composer update to fetch the files before committing in the branch. dev-master is now a v2 alpha. JsonPath constructor now expects a data object. API breaking change, grr!

I'll update the PR... just a couple lines in the CAPx module to fix it or we can just roll back to 1.1.0 release.

old:

``` php
    $jsonParser = new JsonParser();
    $parsed = $jsonParser->get($data, $path);
```

new:

``` php
    $jsonParser = new JsonParser($data);
    $parsed = $jsonParser->get($path);
```

**Comment by mpriest** [comment]
API change: def62e6fedcdaafff89f5e77ed1a33f5038b832b
Do I need to create a new PR?

**Comment by sherakama** [comment]
Lets roll with the new commits. Please send in a PR with the updates.

**Pull request merged**
