### PR TITLE
CAPX-3

### PR DESCRIPTION
**Pull request by RoSk0**
Added field handlers for settings and meta fields.

### CODE REVIEW

**Comment by mpriest** [comment]
Code looks good to me.

**Comment by sherakama** [comment]
Works great. There are a few more values that I would like as a select option but I will create a new ticket/pr for that.

**Comment by mpriest** [comment]
I think that's all the keys Kirill saw in the database.

**Comment by sherakama** [comment]
Yep, this is great. As always I have new expanded ideas and needs.

**Pull request merged**
