### PR TITLE
CAPX-213: Merge the connect and settings forms in to one.

### PR DESCRIPTION
**Pull request by sherakama**
# DO NOT MERGE

---

Please review but do not merge.

Merges the two forms in to one cohesive form.
- Does not display configuration options until connection has been made
- Syncs orgs and schema on connect
- Buttons to manually sync orgs and schema re-worked
- Submit handlers changed.

To test: 
- Install this branch from scratch in a new site. 
- Go to settings page.
- Enter authentication credentials and save.
- Change other configuration options and save.

### CODE REVIEW

**Comment by sherakama** [comment]
@boznik Please review but do not merge. This is going in the 2.x branch in the end.

**Comment by boznik** [comment]
Running "phplint:php" (phplint) task

> > 951 files php linted.

Running "phplint:module" (phplint) task

> > 3 files php linted.

Running "phplint:inc" (phplint) task

> > 18 files php linted.

Done, without errors.

**Comment by boznik** [comment]
This works on php55 but not php54. is that expected?

**Comment by tsui1** [comment]
I think there's a separate branch for php54: https://github.com/SU-SWS/stanford_capx/tree/php54

**Comment by sherakama** [comment]
Yes, the version of Guzzle on the main branches needs 5.5 or greater.

**Comment by boznik** [comment]
ok, this is working as expected.

**Comment by sherakama** [comment]
Great! I'm closing as the code is in 2.x

**Pull request closed without merging**
