### PR TITLE
CAPX-233: Prevents orphan processing when response from API is false

### PR DESCRIPTION
**Pull request by sherakama**
# CAPX-233

Ready for review.

This also fixes an issue where orphans were not being adopted. 

_To test:_
- Install a JSA website
- Check out the 2.x branch
- Create an importer and import a bunch of people 
- Disconnect your internet
- Run the orphan check through the UI or cron
- See orphans show up
- Set all the orphans back to "not orphaned'" in the database
- Check out this branch
- Run the orphan check through the UI or cron
- See no orphans created
- Party

### CODE REVIEW

**Comment by sherakama** [comment]
@josephgknox,

FYI, as you saw the mass orphaning and lack of adoption.

**Comment by jbickar** [comment]
I'm hoping to look at this today, FYI

**Comment by josephgknox** [comment]
@sherakama thanks for keeping me in the loop. When this gets merged, I'll happily pull to Chem and test.

**Comment by jbickar** [comment]
Currently blocked by step 4. I'm afraid I can't do that right now, Dave.

**Comment by sherakama** [comment]
If you have little snitch or something else installed you might be able to block communication to https://api.stanford.edu. Or you could route it with /etc/hosts to something that never responds.

**Comment by sherakama** [comment]
For me, it was easier to yank out a cable from the side of my computer.

**Comment by jbickar** [comment]
TIL: this will have to be backported to the `php54` branch.

Will swap out my PHP to a more recent version and test again.

**Comment by sherakama** [comment]
You can merge this branch directly in to the `php54-2.x` if you want to stay with testing on PHP-5.4.

**Comment by jbickar** [comment]
I like step 11.

**Comment by sherakama** [comment]
It goes to 11

**Pull request merged**
