### PR TITLE
7.x-1.1

### PR DESCRIPTION
**Pull request by jbickar**
@sherakama merge and tag plz

### CODE REVIEW

**Comment by sherakama** [comment]
I see no changes to labels? Did you miss a file in your commit?

**Comment by jbickar** [comment]
Made on 7.x-1.x branch.

https://github.com/SU-SWS/stanford_capx/commit/6036e057ce5c6180a2b1e1ca7b46c1447d2f94fd
https://github.com/SU-SWS/stanford_capx/commit/f767fcee90324ac5c4b8ec10925b6e1955050962

**Comment by jbickar** [comment]
Those changes have been made since 7.x-1.0

**Comment by sherakama** [comment]
Ahh, you branched off the already made changes. Gotcha.

**Pull request merged**
