### PR TITLE
HSDO-441: Static caching of DB results

### PR DESCRIPTION
**Pull request by sherakama**
Turns out lots of calls happen to entity_load. Whodathunkit?

### CODE REVIEW

**Comment by sherakama** [comment]
screen shot 2016-09-22 at 5 06 58 pm

With this patch I get an almost 20% savings on memory and a 7% savings on network bandwidth. Woot.

**Comment by sherakama** [comment]
@jbickar, FYI.

Turns out hook_entity_load is a heavily used hook and even a small db_query can cause load issues.

**Comment by boznik** [comment]
interesting

**Comment by sherakama** [comment]
@boznik, any issues with merging this?

**Comment by boznik** [comment]
looks good, but i haven't tested it yet

**Comment by sherakama** [comment]
Ok, Ill wait.

**Comment by boznik** [comment]
awesome, seeing entity_load times nearly cut in half.
267 soe profiles using entity_load 44,233 without caching goes down to 27,191with caching.

**Comment by sherakama** [comment]
Woot. Thanks for testing GG.

**Pull request merged**
