### PR TITLE
DEVOPS-256: CAPx fatal error with cardinald7 1.0.41 release

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- Update `guzzle` and other dependencies

# Needed By (Date)
- Will be required to push a new version of `cardinald7` and `leland` to get the latest version of `acquia_purge_d8cache` deployed (because the last point release had to be rolled back)

# Criticality
- How critical is this PR on a 1-10 scale? 7/10
- CAPx is broken without it

# Steps to Test

1. Run through the [CAPx Behat tests](https://github.com/SU-SWS/linky_clicky/tree/5.x/includes/features/SU-SWS/stanford_capx)
    1. Difficulty: I'm having trouble getting the "[And I am authenticated with CAPx](https://github.com/SU-SWS/linky_clicky/blob/5.x/includes/features/SU-SWS/stanford_capx/1st_stanford_capx.feature#L9)" step to work.
2. Check out the `DEVOPS-256` branches on ACSF `cardinald7` and `leland` stacks and test as above

# Affected Projects or Products
- CAPx D7
- ACSF cardinald7 and leland

# Associated Issues and/or People
- JIRA ticket: DEVOPS-256

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by pookmish — APPROVED** [review]
that looks more better

**Comment by jbickar** [comment]
What was the trick for the Behat tests?

**Comment by sherakama** [comment]
So your plan is to align the capx version of guzzle with the stack version of guzzle and let the autoloaders fight it out?

You're setting yourself up for breakage again as there is nothing linking those two things together.

**Comment by jbickar** [comment]
There's an issue in the Guzzle issue queue, I should have linked it. They're fighting it out there.

I'll find it.

**Comment by jbickar** [comment]
- [Call to undefined function GuzzleHttp_idn_uri_convert() ](https://github.com/guzzle/guzzle/issues/2511)
- [Avoid functions due to global install conflicts](https://github.com/guzzle/psr7/pull/308)

**Pull request merged**
