### PR TITLE
Added capx_ssp and capx_webauth modules

### PR DESCRIPTION
**Pull request by sherakama**
For integration with single sign on modules.

To Test:
* Check out this branch on a sites site
* Enable the capx_webauth module
* Import your profile as a user entity
* Log in through webauth :D

### CODE REVIEW

**Comment by sherakama** [comment]
@zchandler Happy Thanksgiving

**Comment by jbickar** [comment]
Fatal error on Sites. This needs backported to the `php54` branch

**Comment by jbickar** [comment]
Are we missing a step in these test instructions? Is the point to import the user entity from CAP and assign it a role, before the user has logged in with SSO? Or is the point to add additional fields to the User bundle and be able to map those from CAP? I'm not understanding the use case here.

**Comment by sherakama** [comment]
Ah shoot right...

Check out the php54-2.x branch on sites and give it another go. I accidentally merged this work in to that branch already. Don't ask how.

The point of these modules is to allow a site owner to import a group of users so that they can log in with webauth and edit their profile. Their profile being their user entity. They will most likely have additional fields on them. No, the role mapping should stay within role mapping assignments in webauth/ssp. 

Please try again.

**Comment by jbickar** [comment]
on `php54-2.x`:
2016-12-02-115538-screenshot

**Comment by jbickar** [comment]
Oh, that's fancypants.

2016-12-02-12146-screenshot

**Comment by jbickar** [comment]
So the `sso` branch is working, but I'm hitting 500 errors with the `php54-2.x` branch.

**Comment by jbickar** [comment]
Strike that.

**Comment by sherakama** [comment]
2 new issues from this approach...

1. Email is not always available and users are still created
2. Email is not always available and an empty webauth entry is created.
3. Email is not always available and webauth user is not linked up when logged in.
4. Email and sunet id is not always matching. Need to hard fetch for webauth.

**Comment by jbickar** [comment]
Yeah, so if one of these submodules is enabled, force `sunetid@stanford.edu` as the email address even if the user has a different preferred email listed in the CAP API. I think.

**Comment by sherakama** [comment]
Ok, revisions are made.

I updated the DRPL675 website with the latest.

@jbickar Please have another go.

**Comment by jbickar** [comment]
The `php54-2.x` branch still creates users without email addresses. Is that intentional?

WebAuth integration is working as expected now.

**Comment by sherakama** [comment]
The no-email thing is not something I plan to fix. If they have it hidden on the API then it should stay that way. I am able to cheat the authmap for the log in and the user should fix their email at that point.

**Comment by jbickar** [comment]
User can't fix their email if it's mapped from CAP:

2016-12-07-10540-screenshot

**Comment by jbickar** [comment]
Integration with SAML is _not_ working. A new user was created via SAML with a different `uid` than the one that was created via CAPx import.

**Comment by sherakama** [comment]
@jbickar,

Ok, you convinced me to force the email address and auth to the sunetid. Your user was not connecting to the anchorage ssp because your email was not available. I have change the authmap to now use your sunet.

**Comment by jbickar** [comment]
1. WebAuth working as designed
2. Not working on Anchorage; will rebuild the site (not sure if it's been rebuilt with the latest code)

**Comment by jbickar** [comment]
w00t. Working as expected on Anchorage.

**Comment by jbickar** [comment]
This will need:

1. Documentation in the README files about expected behavior when the user's email address is not `sunetid@stanford.edu`.
2. Documentation in the README files about the use case that these modules fulfill.
3. Cleanup of boilerplate stuff like https://github.com/SU-SWS/stanford_capx/pull/88/files#diff-509c3fff7f999d216bbc426eb050b759R6

**Comment by jbickar** [comment]
@jbickar likes this.

**Comment by zchandler** [comment]
Thanks for all the hard work you guys!

**Pull request merged**
